HackerNews/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :comments do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
 
 
  resources :contributions do
    resources :comments
  end
  
  resources :users
  root 'contributions#index'
  get '/ask' => 'contributions#ask'
  
  get "/login", to: redirect("/auth/google_oauth2")
  
  get "/auth/google_oauth2/callback", to: "sessions#create"
  
  get "/logout", to:  "sessions#destroy"
  
  get "/contributions_user", to: "contributions#contributions_user"
  
  get "/comments_user", to: "comments#comments_user"

  get "/newest", to: "contributions#newest"
  resource :session, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HackerNews/app/models/user.rb
class User < ApplicationRecord
    
    validates :APIKey, uniqueness: true
    
    def self.form_omniauth(response)
        User.find_or_create_by(email: response["info"]["email"]) do |u|
            u.name = response["info"]["name"]
            u.email = response["info"]["email"]
        end
    end
    
end

HackerNews/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json {
        @contributions = Contribution.where(:user_id => @user.id)
        @comments = Comment.where(:user_id => @user.id)
        @karma = 0
        @contributions.each do |contribution|
          @karma += contribution.points
        end
        @comments.each do |comment|
          @karma += comment.points
        end
        @users_json = render_to_string('show.json.jbuilder', locals: { user: @user, karma: @karma})
        JSON.pretty_generate(@users_json)
      }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if request.format.json? and User.find_by(:APIKey => request.headers["X-API-KEY"]).id!=params[:id].to_i
      render json: {message: "You are not logged as this user"}, status: :forbidden
      return
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :about)
    end
end

HackerNews/app/helpers/users_helper.rb
module UsersHelper
end

HackerNews/app/views/users/_form.html.erb
<p id="notice"><%= notice %></p>
<center>
<%= form_with(model: user) do |form| %>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'contributions/header' %>
  </tbody>
  <tbody>
    <tr>
      <td>
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
            <% if user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% user.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <tr><td valign="top">name:</td><td>
              <%= form.text_field :name %>
            </div>
          
            <div class="field">
              <tr><td valign="top">email:</td><td>
              <%= form.text_field :email %>
            </div>
            
            <div class="field">
              <tr><td valign="top">about:</td><td>
              <%= form.text_field :about %>
            </div>
          
            <div class="actions">
              <%= form.submit %>
            </div>
        </table>
      </td>
    </tr>
  </tbody>
</table>
<% end %>
</center>

HackerNews/app/views/users/edit.html.erb
    <%= render 'form', user: @user %>

HackerNews/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

HackerNews/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

HackerNews/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'contributions/header' %>
    <tr>
      <td>
        <table border="0">
          <tbody>
            <tr class="athing"></tr>
            <td valign="top">name:</td>
            <td>
              <a class="hnuser"><%= @user.name %></a>
            </td>
            <tr>
              <td valign="top">created:</td>
              <td>
                <a><%= "#{time_ago_in_words(@user.created_at)} ago" %></a>
              </td>
            </tr>
            <tr>
              <td valign="top">karma:</td>
              <td>
                <% @contributions = Contribution.where(:user_id => @user.id) %>
                <% @comments = Comment.where(:user_id => @user.id) %>
                <% @user_points = 0 %>
                <% @contributions.each do |contribution| %>
                  <% @user_points += contribution.points %>
                <% end %>
                <% @comments.each do |comment| %>
                  <% @user_points += comment.points %>
                <% end %>
                <%= @user_points %>
              </td>
            </tr>
            <tr>
              <td valign="top">about:</td>
              <td>
                <a href=""><%= @user.about %></a>
              </td>
            </tr>
            <tr>
              <td valign="top">email:</td>
              <td>
                <a href=""> <%= @user.email %></a>
              </td>
            </tr>
            <tr>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
        <% if logged_in? && @user.id == current_user.id %>
          <%= link_to 'edit', edit_user_path(@user) %><br>
        <% end %>
        <%= link_to 'submissions', contributions_user_path(:user_id => @user.id) %><br>
        <%= link_to 'comments', comments_user_path(:user_id => @user.id) %><br>
        <% if logged_in? && @user.id == current_user.id %>
          <%= link_to 'upvoted submissions', contributions_user_path(:upvoted => 0) %><br>
          <%= link_to 'upvoted comments', comments_user_path(:upvoted => 0) %><br>
          <%= 'APIKey:' %>
          <%= @user.APIKey %><br>
        </tr>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
</center>