HackerNews/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :comments do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
 
 
  resources :contributions do
    resources :comments
  end
  
  resources :users
  root 'contributions#index'
  get '/ask' => 'contributions#ask'
  
  get "/login", to: redirect("/auth/google_oauth2")
  
  get "/auth/google_oauth2/callback", to: "sessions#create"
  
  get "/logout", to:  "sessions#destroy"
  
  get "/contributions_user", to: "contributions#contributions_user"
  
  get "/comments_user", to: "comments#comments_user"

  get "/newest", to: "contributions#newest"
  resource :session, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HackerNews/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, :dependent => :destroy
end

HackerNews/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy vote unvote]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @contribution = Contribution.find(params[:contribution_id])
    @comment = @contribution.comments.new(parent_id: params[:parent_id])
  end

  # GET /comments/1/edit
  def edit
  end
  
  #GET /comments_user or /comments_user.json
  def comments_user
    respond_to do |format|
      format.html{render :comments_user}
      format.json{
        if params.has_key?(:upvoted)
          @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
          if @current_user.nil? or request.headers["X-API-KEY"].nil?
            render :json => {message: "Please insert a valid API Key" }, status: :unauthorized
          else
            @votes = VotesComment.where(user_id: User.find_by(id: @current_user.id))
            @comments = Comment.none
            @votes.each do |vote|
              @comments = @comments + Comment.where(id: vote.comment_id)
            end
            render json: render_to_string('index.json.jbuilder', locals: { comments: @comments })
          end
        else
          @comments = Comment.where(:user_id => params[:user_id])
          render json: render_to_string('index.json.jbuilder', locals: { comments: @comments })
        end
      }
    end
  end
  
   #PUT /vote
  def vote
    @vote = VotesComment.new
    @vote.comment_id = @comment.id
    if request.format.json?
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      has_voted  =  VotesComment.find_by(user_id: @current_user.id, comment_id: @comment.id)!= nil
      can_vote = @comment.user_id != @current_user.id
      if has_voted or !can_vote
        render json: {message: "You cannot vote this comment"}, status: :unauthorized
        return
      end
      @vote.user_id = @current_user.id
    else
      @vote.user_id = current_user.id
    end
    respond_to do |format|
      if @vote.save
        @comment.points = @comment.points + 1 
        @comment.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: {message: "Comment voted successfully"} }
      else
        format.html { redirect_back fallback_location: @comment }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #PUT /unvote
  def unvote
    if request.format.json?
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      @vote = VotesComment.find_by(user_id: @current_user.id, comment_id: @comment.id)
      has_voted  =  @vote != nil
      can_vote = @comment.user_id != @current_user.id
      if !has_voted or !can_vote
        render json: {message: "You cannot unvote this comment"}, status: :unauthorized
        return
      end
    else
      @vote =  VotesComment.find_by(user_id: User.find_by(id: session[:user_id]).id, comment_id: @comment.id)
    end
    respond_to do |format|
      if @vote.destroy
        @comment.points = @comment.points - 1 
        @comment.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: {message: "Comment unvoted successfully"} }
      else
        format.html { redirect_back fallback_location: @comment }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /comments or /comments.json
  def create
    #@contribution = Contribution.find(params[:contribution_id])
    #@comment = @contribution.comments.new(comment_params)
    @comment = Comment.new(comment_params)
    @comment.points = 0
    if request.format.json?
      if @comment.contribution_id == nil or Contribution.find_by(id: @comment.contribution_id) == nil
        render :json => {message: "Please insert a valid contribution id" }, status: :unauthorized
        return
      end
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      if @current_user.nil? or request.headers["X-API-KEY"].nil?
        render :json => {message: "Please insert a valid API Key" }, status: :unauthorized
        return
      else
        @comment.user_id = @current_user.id
        if(params[:parent_id] != nil)
          @parent = Comment.find_by(id: params[:parent_id])
          if(@parent.contribution_id != @comment.contribution_id)
            render :json => {message: "The parent does not belong to the contribution" }, status: :unauthorized
            return
          else
            @comment.parent_id = params[:parent_id]
          end
        end
      end
    end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to controller: 'contributions' , action: 'show', id: @comment.contribution_id}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to Contribution.find_by(:id => @comment.contribution_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :text, :contribution_id, :parent_id, :points)
    end
end

HackerNews/app/helpers/comments_helper.rb
module CommentsHelper
end

HackerNews/app/views/comments/_comments_user.html.erb
<p id="notice"><%= notice %></p>

<% @comments.each do |comment| %>
  <table border="0">
    <tr class="athing comtr">
      <td>
        <table border="0">
          <tr>
            <td valign="top" class="votelinks">
              <% if logged_in? %>
                  <%has_voted_comment  =  VotesComment.find_by(user_id: User.find_by(id: session[:user_id]).id,  comment_id: comment.id)!= nil  %>
                  <% can_vote_comment = comment.user_id != User.find_by(id: session[:user_id]).id and logged_in? %>
                  <% if !has_voted_comment and can_vote_comment %>
                    <center>
                      <span>
                          <%= link_to image_tag("grayarrow.gif") ,  vote_comment_path(comment), method: :put %>
                      </span>
                    </center>
                  <% elsif !has_voted_comment and !can_vote_comment%>
                    <center>
                      <span>
                        *
                      </span>
                    </center>
                  <% end %> 
                  <% else %>
                    <center>
                      <span>
                        *
                      </span>
                    </center>
                  <%end%>
            </td>
            <td class="default">
              <div style="margin-top:2px; margin-bottom:-10px;">
                <span class="comhead">
                  <% @contribution = Contribution.find(comment.contribution_id)  %>
                  <a><%= link_to User.find_by(:id => comment.user_id).name,  User.find_by(:id => comment.user_id)%></a> 
                  <span class="age">
                    <a href=""><%= "#{time_ago_in_words(comment.created_at)} ago" %></a>
                  </span>
                  |
                  <span>
                    <a><%= link_to "on: #{@contribution.title}", @contribution %></a>
                  </span>
                  
                  <% if has_voted_comment %>
                    |
                    <span>
                    <%= link_to 'unvote',  unvote_comment_path(comment), method: :put %>
                    </span>
                  <% end %>
                  
                  <% if logged_in? && comment.user_id == current_user.id && Comment.where(parent_id: comment.id).size == 0 %>
                    |
                    <%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
                  <% end %>
                </span>
              </div>
                
              <br>
              <div class="card">
                <div class="card-body">
                  <%= comment.text %>
                  <br>
                  <%= link_to 'reply', new_contribution_comment_path(@contribution, parent_id: comment.id) %>
                </div>
              </div>
              <%= render 'comments/show', :object => @comments = Comment.where(contribution_id: @contribution.id, parent_id: comment.id) %>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
<% end %>

HackerNews/app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form method="post" action="/comments">
    <% if logged_in? %>
      <% comment = @new_comment %>   
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :contribution_id, value: contribution_id %>
      <%= form.hidden_field :parent_id, value: nil %>
      <%= form.hidden_field :points, value: 1 %>
      <textarea name="comment[text]" rows="6" cols="60" required minlength="3" required></textarea> <br />
      <br />
      <input type="submit" value="add comment" />
    <% else %>
    <textarea name="nil" rows="6" cols="60"></textarea> <br />
      <br />
      <button><%= link_to "add comment", login_path %></button>
    <% end %>
  </form>

<% end %>

HackerNews/app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= reply.text %>
    <br>
    <%= link_to 'reply', new_contribution_comment_path(@contribution, parent_id: reply.id) %>
  </div>
</div>

HackerNews/app/views/comments/_reply_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form method="post" action="/comments">
    <% comment = @new_comment %>   
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :contribution_id, value: params[:contribution_id] %>
    <%= form.hidden_field :parent_id, value: params[:parent_id] %>
    <%= form.hidden_field :points, value: 1 %>
    <textarea name="comment[text]" rows="6" cols="60" required minlength="3" required></textarea> <br />
    <br />
    <input type="submit" value="reply" />
  </form>

<% end %>

HackerNews/app/views/comments/_show.html.erb
<p id="notice"><%= notice %></p>

<% @comments.each do |comment| %>
  <table border="0">
    <tr class="athing comtr">
      <td>
        <table border="0">
          <tr>
            <td valign="top" class="votelinks">
              <% if logged_in? %>
                  <%has_voted_comment  =  VotesComment.find_by(user_id: User.find_by(id: session[:user_id]).id,  comment_id: comment.id)!= nil  %>
                  <% can_vote_comment = comment.user_id != User.find_by(id: session[:user_id]).id and logged_in? %>
                  <% if !has_voted_comment and can_vote_comment %>
                    <center>
                      <span>
                          <%= link_to image_tag("grayarrow.gif") ,  vote_comment_path(comment), method: :put %>
                      </span>
                    </center>
                  <% elsif !has_voted_comment and !can_vote_comment%>
                    <center>
                      <span>
                        *
                      </span>
                    </center>
                  <% end %> 
                  <% else %>
                    <center>
                      <span>
                        *
                      </span>
                    </center>
                  <%end%>
            </td>
            <td class="default">
              <div style="margin-top:2px; margin-bottom:-10px;">
                <span class="comhead">
                  <a><%= link_to User.find_by(:id => comment.user_id).name,  User.find_by(:id => comment.user_id)%></a> 
                  <span class="age">
                    <a href=""><%= "#{time_ago_in_words(comment.created_at)} ago" %></a>
                  </span>
                  
                  <% if has_voted_comment %>
                    |
                    <span>
                    <%= link_to 'unvote',  unvote_comment_path(comment), method: :put %>
                    </span>
                  <% end %> 
                  
                  <% if logged_in? && comment.user_id == current_user.id && Comment.where(parent_id: comment.id).size == 0 %>
                    |
                    <%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
                  <% end %>
                </span>
              </div>
                
              <br>
              <div class="card">
                <div class="card-body">
                  <%= comment.text %>
                  <br>
                  <%= link_to 'reply', new_contribution_comment_path(@contribution, parent_id: comment.id) %>
                </div>
              </div>
              <%= render 'comments/show', :object => @comments = Comment.where(contribution_id: @contribution.id, parent_id: comment.id) %>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
<% end %>

HackerNews/app/views/comments/comments_user.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'contributions/header' %>
    <tr>
      <td>
        <table border="0" cellpadding="0" cellspacing="0" class="itemlist">
          <tbody>
            <tr class="athing">
              <% if params.has_key?(:upvoted) %>
                <% @votes = VotesComment.where(user_id: User.find_by(id: current_user.id)) %>
                <% @comments = Comment.none %>
                <% @votes.each do |vote| %>
                  <% @comments = @comments + Comment.where(id: vote.comment_id) %>
                <% end %>
              <% else %>
                <% @comments = Comment.where(user_id: params["user_id"]) %>
              <% end %>
              <td align="right" valign="top" class="title">
                <%= render 'comments_user', :object => @comments = @comments%>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
</center>

HackerNews/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

HackerNews/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'contributions/header' %>
    <tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tbody><tr class="athing" id="26831162">

    <% i=1 %>
              <% @comments.each do |comment| %>
              <% if logged_in? && current_user.id == comment.user_id %>
                <tr class="athing comtr" id="26590395"><td>
                  <table border="0">  
                    <tbody><tr>    
                      <td class="ind"><img src="s.gif" height="1" width="0"></td><td valign="top" class="votelinks">
                        <center><font color="#ff6600">*</font><br>
                          <img src="s.gif" height="1" width="14"></center>    </td><td class="default"><div style="margin-top:2px; margin-bottom:-10px;"><span class="comhead">
                            <span class="score" id="score_26590395"> <%= comment.points %> points</span> by 
                            <%= link_to User.find(comment.user_id).name, user_path(User.find(comment.user_id)) %></a>
                            <span class="age"><a href="item?id=26590395"><a><%= "#{time_ago_in_words(comment.created_at)} ago" %></a></a></span> <span id="unv_26590395"></span><span class="par"> | <a href="item?id=26590393">parent</a></span> <a class="togg" n="1" href="javascript:void(0)" onclick="">[–]</a>          <span class="storyon"> | on: <a href=""><%=Contribution.find(comment.contribution_id).title%></a></span>
                            </span></div><br><div class="comment">
                            <span class="commtext c00"><%= comment.text %></span>
                            <div class="reply">        <p><font size="1">
                            </font>
                            </p></div>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  </td>
                </tr>
                <% end %>
                <% i+=1 %>
                
              <% end %>
  </tbody>
</table>
</center>

HackerNews/app/views/comments/new.html.erb
<html lang="en" op="reply">
  <head>
    <meta name="referrer" content="origin">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="news.css?gwUwIJb2O4bc3uwDx50E">
    <link rel="shortcut icon" href="favicon.ico">
    <title>Add Comment | Hacker News</title>
  </head>
<body>
  <center>
    <table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tbody>
        <tr>
          <td bgcolor="#ff6600">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
              <tbody>
                <tr>
                  <td style="width:18px;padding-right:4px">
                    <a href=/contributions>
                      <img src="y18.gif" width="18" height="18" style="border:1px white solid;">
                    </a>
                  </td>
                  <td style="line-height:12pt; height:10px;">
                    <span class="pagetop">
                      <b>Add Comment</b>
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <tr id="pagespace" title="Add Comment" style="height:10px"></tr>
        <tr>
          <td>
            <table class="fatitem" border="0">
              <tbody>
                <tr class="athing" id="26910060">    
                  <td class="ind"></td>
                  <td valign="top" class="votelinks">
                    <center>
                      <a id="up_26910060" onclick="return vote(event, this, &quot;up&quot;)" href="vote?id=26910060&amp;how=up&amp;auth=0dfc6dd2e89cbdf39e53f44e34760222bcca1674&amp;goto=reply%3Fgoto%3Ditem%253Fid%253D26909488%252326910060%26id%3D26910060#26910060">
                        <div class="votearrow" title="upvote"></div>
                      </a>
                    </center>    
                  </td>
                <td class="default">
                  <div style="margin-top:2px; margin-bottom:-10px;">
                    <span class="comhead">
                      <a href="/users/<%=Comment.find_by(:id => @comment.parent_id).user_id%>" class="hnuser"> <%= User.find_by(:id => Comment.find_by(:id => @comment.parent_id).user_id).name %></a> 
                      <span class="age">
                        <a href="/contributions/<%=@comment.contribution_id%>"> <%= time_ago_in_words(Comment.find_by(:id => @comment.parent_id).created_at) %></a>
                      </span> 
                      <span id="unv_26910060"></span>
                      <span class="par">
                         | 
                        <a href="/contributions/<%=@comment.contribution_id%>">parent</a>
                      </span> 
                      <a class="togg" n="3" href="javascript:void(0)" onclick="return toggle(event, 26910060)">[–]</a> 
                      <span class="storyon">
                         | on:  
                        <a href="/contributions/<%=@comment.contribution_id%>"><%= Contribution.find_by(:id => @comment.contribution_id).title%></a>
                      </span>
                    </span>
                  </div>
                  <br>
                  <div class="comment">
                    <span class="commtext c00">&gt; <%= Comment.find_by(:id => @comment.parent_id).text%>
                    <div class="reply"></div>
                  </span>
                </div>
              </td>
            </tr>
            <tr style="height:10px"></tr>
            <tr>
              <td colspan="2"></td>
              <td>
                <%= render 'reply_form', comment: @comment %>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
  </table>
  </center>
  <script type="text/javascript" src="hn.js?gwUwIJb2O4bc3uwDx50E"></script>
</body>
</html>

HackerNews/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Contribution:</strong>
  <%= @comment.contribution_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>