HackerNews/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :comments do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
 
 
  resources :contributions do
    resources :comments
  end
  
  resources :users
  root 'contributions#index'
  get '/ask' => 'contributions#ask'
  
  get "/login", to: redirect("/auth/google_oauth2")
  
  get "/auth/google_oauth2/callback", to: "sessions#create"
  
  get "/logout", to:  "sessions#destroy"
  
  get "/contributions_user", to: "contributions#contributions_user"
  
  get "/comments_user", to: "comments#comments_user"

  get "/newest", to: "contributions#newest"
  resource :session, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HackerNews/app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :delete_all
  #if :type_url == true
    #validates :url, url: :url
  #end
end

HackerNews/app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: %i[ show edit update destroy vote unvote]
  # GET /contributions or /contributions.json
  def index
    @contributions = Contribution.all
  end
  
  def newest
    @contributions = Contribution.all.order(created_at: :desc)
    render "contributions/index"
  end

  # GET /contributions/1 or /contributions/1.json
  def show
    @comment = Comment.new
    respond_to do |format|
      format.html{render :show, location: @contribution}
      format.json{
        @comments = Comment.where(contribution_id: @contribution.id)
        render json: render_to_string('show.json.jbuilder', locals: { contribution: @contribution, comments: @comments })
      }
    end
  end

  # GET /ask
  def ask
    @contributions =  Contribution.where(type_url: false);
    respond_to do |format|
      format.html {render :ask, status: :unprocessable_entity }
      format.json { render json: @contributions}
    end
  end
  
  # GET /contributions/new
  def new
    @contribution = Contribution.new
    
  end

  # GET /contributions/1/edit
  def edit
  end
  
  #GET /contributions_user or /contributions_user.json
  def contributions_user
    respond_to do |format|
      format.html{render :contributions_user}
      format.json{
        if params.has_key?(:upvoted)
          @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
          if @current_user.nil? or request.headers["X-API-KEY"].nil?
            render :json => {message: "Please insert a valid API Key" }, status: :unauthorized
          else
            @votes = Vote.where(user_id: User.find_by(id: @current_user.id))
            @contributions = Contribution.none
            @votes.each do |vote|
              @contributions = @contributions + Contribution.where(id: vote.contribution_id)
            end
            render json: render_to_string('index.json.jbuilder', locals: { contributions: @contributions })
          end
        else
          @contributions = Contribution.where(:user_id => params[:user_id])
          render json: render_to_string('index.json.jbuilder', locals: { contributions: @contributions })
        end
      }
    end
  end
  
  #PUT /vote
  def vote
    @vote = Vote.new
    @vote.contribution_id = @contribution.id
    if request.format.json?
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      has_voted  =  Vote.find_by(user_id: @current_user.id, contribution_id: @contribution.id)!= nil
      can_vote = @contribution.user_id != @current_user.id
      if has_voted or !can_vote
        render json: {message: "You cannot vote this contribution"}, status: :unauthorized
        return
      end
      @vote.user_id = @current_user.id
    else
      @vote.user_id = current_user.id
    end
    respond_to do |format|
      if @vote.save
        @contribution.points = @contribution.points + 1 
        @contribution.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: {message: "Voted successfully"} }
      else
        format.html { redirect_back fallback_location: @contribution }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end
  
    
  #PUT /unvote
  def unvote
    if request.format.json?
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      @vote =  Vote.find_by(user_id: @current_user.id, contribution_id: @contribution.id)
      has_voted = @vote != nil
      can_vote = @contribution.user_id != @current_user.id
      if !has_voted or !can_vote
        render json: {message: "You cannot unvote this contribution"}, status: :unauthorized
        return
      end
    else
      @vote =  Vote.find_by(user_id: User.find_by(id: session[:user_id]).id, contribution_id: @contribution.id)
    end
    respond_to do |format|
      if @vote.destroy
        @contribution.points = @contribution.points - 1 
        @contribution.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: {message: "Unvoted successfully"} }
      else
        format.html { redirect_back fallback_location: @contribution }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /contributions or /contributions.json
  def create
    #@Contribution.user_id = 1
    @contribution = Contribution.new(contribution_params)
    
    if request.format.json?
      @current_user = User.find_by(:APIKey => request.headers["X-API-KEY"])
      if @current_user.nil? or request.headers["X-API-KEY"].nil?
        render :json => {message: "Please insert a valid API Key" }, status: :unauthorized
        return
      elsif @contribution.url.empty? and @contribution.ask.empty?
          render :json => {message: "Please enter either an URL or a message" }, status: :unprocessable_entity
          return
      else
        @contribution.user_id = @current_user.id
      end
    else
      @contribution.user_id= current_user.id
    end
    
    @contribution.points = 0
    if @contribution.url.empty?
        @contribution.type_url = false
    else @contribution.type_url = true
    end
    
    if @contribution.type_url
      @repeated = Contribution.find_by(:url => @contribution.url)
    else @repeated = nil
    end
    
    respond_to do |format|
      if @repeated != nil
        format.html { redirect_to contribution_path(@repeated) }
        format.json {
          render :json => {message: "This url has already been submited in contribution: " + @repeated.id.to_s}, status: :unauthorized
          #@comments = Comment.where(contribution_id: @repeated.id)
          #render json: render_to_string('show.json.jbuilder', locals: { contribution: @repeated, comments: @comments })
          #render :show, status: :ok, location: @repeated
          return
        }
      else if @contribution.save
        if @contribution.type_url && !@contribution.ask.empty?
          @comment = Comment.create({:user_id => @contribution.user_id, :text => @contribution.ask, :contribution_id => @contribution.id, :parent_id => nil, :points => 0})
        end
        format.html { redirect_to contributions_path }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # PATCH/PUT /contributions/1 or /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: "Contribution was successfully updated." }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1 or /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: "Contribution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contribution_params
      params.require(:contribution).permit(:title, :url, :ask, :user_id, :type_url)
    end
end

HackerNews/app/helpers/contributions_helper.rb
module ContributionsHelper
end

HackerNews/app/views/contributions/_contribution.html.erb
<td valign="top" class="votelinks">
<% if logged_in? %>
  <% has_voted  =  Vote.find_by(user_id: User.find_by(id: session[:user_id]).id, contribution_id: contribution.id)!= nil  %>
  <% can_vote = contribution.user_id != User.find_by(id: session[:user_id]).id and logged_in? %>
  
  <% if !has_voted and can_vote %>
    <center>
      <span>
        <%= link_to image_tag("grayarrow.gif") ,  vote_contribution_path(contribution), method: :put %>
      </span>
    </center>
  <% elsif !has_voted and !can_vote%>
    <center>
      <span>
        *
      </span>
    </center>
  <% end %> 
<% else %>
  <center>
    <span>
      *
    </span>
  </center>
<%end%>
</td>
<td class="title">
  <a>
    <% if contribution.type_url %>
      <%= link_to contribution.title, "#{contribution.url}", :target => "_blank" %>
    <% else %>
      <%= link_to contribution.title, contribution %>
    <% end %>
  </a>
</td>
<tr>
<td colspan="2"></td>
<td class="subtext">
  <span class="" id=""><%= contribution.points %> points</span> by 
 
  <%= link_to User.find(contribution.user_id).name, user_path(User.find(contribution.user_id)) %></a>
  <a href="" class=""></a> 
  <span class="age">
    <a><%= link_to "#{time_ago_in_words(contribution.created_at)} ago", contribution %></a>
  </span>
    <% if has_voted %>
    |
    <span>
    <%= link_to 'unvote',  unvote_contribution_path(contribution), method: :put %>
    </span>
  <% end %>
  <% if logged_in? && contribution.user_id == current_user.id %>
    |
    <%= link_to 'delete', contribution, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
  <% end %>
  |
  <a><%= link_to "#{Comment.where(contribution_id: contribution.id).size} comments", contribution %></a>
</td>
</tr>
<tr class="spacer" style="height:5px"></tr>

HackerNews/app/views/contributions/_form.html.erb
<%= form_with(model: contribution) do |form| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
        <% contribution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <center>
    <table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <%= render 'header' %>
      <tbody>
        <tr>
          <td>
            <form method="post" action="/contributions">
              <input type="hidden" name="fnid">
              <input type="hidden" name="fnop" value="submit-page">
              <script type="text/javascript">function tlen(el) { var n = el.value.length - 80; el.nextSibling.innerText = n > 0 ? n + ' too long' : ''; }</script>
              <% contribution = @new_contribution %>         
              <table border="0">
                <tbody>
                  <tr>
                    <td>title</td>
                    <td>
                      <input type="text" name="contribution[title]" value="" size="50" oninput="tlen(this)" onfocus="tlen(this)">
                      <span style="margin-left:10px"></span>
                    </td>
                  </tr>
                  <tr>
                    <td>url</td>
                    <td><input type="text" name="contribution[url]" value="" size="50"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td><b>or</b></td>
                  </tr>
                  <tr>
                    <td>text</td>
                    <td><textarea name="contribution[ask]" rows="4" cols="49"></textarea></td>
                  </tr>
                  <tr><td></td><td></td></tr>
                  <tr>
                    <td></td>
                    <td><input type="submit" value="submit"></td>
                  </tr>
                  <tr style="height:20px"></tr>
                  <tr>
                    <td></td>
                    <td>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.
                      <br>
                    </td>
                  </tr>
                </tbody>
              </table>
            </form>
          </td>
        </tr>
      </tbody>
    </table>
  </center>


<% end %>

HackerNews/app/views/contributions/_header.html.erb
<tr>
  <td bgcolor="#ff6600">
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
      <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=/contributions>
              <img src="../y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="hnname">
              <a href="/contributions">Hacker News</a></b>
              <a href="/newest">new</a>
              <% if logged_in? %>
                |
                <a><%= link_to "threads", comments_user_path(:user_id => current_user.id)%></a>
              <% end %>
              |
              <a href="/ask">ask</a>
              |
              <% if logged_in? %>
                <a href="/contributions/new">submit</a>
              <% else %>
                <a href="<%= login_path %>">submit</a>
              <% end %>
            </span>
          </td>
          <td style="text-align:right;padding-right:4px;">
            <span class="pagetop">
              <% if logged_in? %>
                <span>
                  <%= link_to current_user.name, current_user%>
                  <% @user_contributions = Contribution.where(:user_id => current_user.id) %>
                  <% @user_comments = Comment.where(:user_id => current_user.id) %>
                  <% @user_points = 0 %>
                  <% @user_contributions.each do |contribution| %>
                    <% @user_points += contribution.points %>
                  <% end %>
                  <% @user_comments.each do |comment| %>
                    <% @user_points += comment.points %>
                  <% end %>
                  <%= "(#{@user_points})" %>
                  |
                  <%= link_to "logout", logout_path %>
                </span>
              <% else %>
                <%= link_to "login", login_path %>
              <% end %>
            </span>
          </td>
        </tr>
      </tbody>
    </table>
  </td>
</tr>
<tr id="pagespace" title="" style="height:10px"></tr>

HackerNews/app/views/contributions/ask.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'header' %>
    <tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tbody><tr class="athing" id="26831162">

    <% i=1 %>
              <% @contributions.each do |contribution| %>
                <td align="right" valign="top" class="title">
                  <span class="rank"><%= i %>.</span>
                  <%= render 'contribution', contribution: contribution %>
                </td>
                
                <% i+=1 %>
              <% end %>
  </tbody>
</table>
</center>

HackerNews/app/views/contributions/contributions_user.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'header' %>
    <tr>
      <td>
        <table border="0" cellpadding="0" cellspacing="0" class="itemlist">
          <tbody>
            <tr class="athing">
              <% i=1 %>
              <% if params.has_key?(:upvoted) %>
                <% @votes = Vote.where(user_id: User.find_by(id: current_user.id)) %>
                <% @contributions = Contribution.none %>
                <% @votes.each do |vote| %>
                  <% @contributions = @contributions + Contribution.where(id: vote.contribution_id) %>
                <% end %>
              <% else %>
                <% @contributions = Contribution.where(user_id: params["user_id"]) %>
              <% end %>
              <% @contributions.each do |contribution| %>
                <td align="right" valign="top" class="title">
                  <span class="rank"><%= i %>.</span>
                  <%= render 'contribution', contribution: contribution %>
                </td>
                
                <% i+=1 %>
              <% end %>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
</center>

HackerNews/app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

HackerNews/app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <%= render 'header' %>
    <tr>
      <td>
        <table border="0" cellpadding="0" cellspacing="0" class="itemlist">
          <tbody>
            <tr class="athing">
              <% i=1 %>
              <% @contributions.each do |contribution| %>
                <td align="right" valign="top" class="title">
                  <span class="rank"><%= i %>.</span>
                  <%= render 'contribution', contribution: contribution %>
                </td>
                
                <% i+=1 %>
                
              <% end %>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
</center>

HackerNews/app/views/contributions/new.html.erb
<%= render 'form', contribution: @contribution %>

HackerNews/app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
  <%= render 'header' %>
    <tr>
      <td>
        <table class="fatitem" border="0">
          <tbody>
            <tr class="athing">
              <td align="right" valign="top" class="title">
                <span class="rank"></span>
              </td>      
              
              
              <td valign="top" class="votelinks">
                <% if logged_in? %>
                  <% has_voted  =  Vote.find_by(user_id: User.find_by(id: session[:user_id]).id, contribution_id: @contribution.id)!= nil  %>
                  <% can_vote = @contribution.user_id != User.find_by(id: session[:user_id]).id and logged_in? %>
                      
                  <% if !has_voted and can_vote %>
                    <center>
                      <span>
                        <%= link_to image_tag("grayarrow.gif") ,  vote_contribution_path(@contribution), method: :put %>
                      </span>
                    </center>
                  <% elsif !has_voted and !can_vote%>
                    <center>
                      <span>
                        *
                      </span>
                    </center>
                  <% end %> 
                <% else %>
                  <center>
                    <span>
                      *
                    </span>
                  </center>
                <%end%>
              </td>
              
              
              <td class="title">
                  <% if @contribution.type_url %>
                  <a href=<%= @contribution.url %> ><%= @contribution.title %></a>
                  <span class="sitebit comhead">
                    (
                     <span><%= @contribution.url %></span>
                    )
                </span>
                  <% else %>
                    <a><%= @contribution.title %></a>
                  <% end %>
              </td>
            </tr>
            
            <tr>
              <td colspan="2"></td>
              <td class="subtext">
                <span class="score" ><%= @contribution.points %> points</span> by 
                <a><%= link_to User.find_by(:id => @contribution.user_id).name,  User.find_by(:id => @contribution.user_id)%></a>
                <span class="age">
                  <a href=""><%= "#{time_ago_in_words(@contribution.created_at)} ago" %></a>
                </span> |
                <% if has_voted %>
                    <span>
                    <%= link_to 'unvote',  unvote_contribution_path(@contribution), method: :put %>
                    </span> |
                <% end %>  
                <a><%= link_to "#{Comment.where(contribution_id: @contribution.id).size} comments", @contribution %></a>              
              </td>
            </tr>
            
            <tr class="spacer" style="height:10px"></tr>
            <tr>
              <% if !@contribution.type_url %>
                <td colspan="2"></td>
                <td colspan="2"><%= @contribution.ask %></td>
              <% end %>
            </tr>
            <tr>
              <td colspan="2"></td>
              <td>
                <%= render 'comments/form', {comment: @comment, contribution_id: @contribution.id} %>
                <!--%= link_to 'reply', new_contribution_comment_path(@contribution, parent_id: nil) %-->
              </td>
            </tr>
            
            
            <table border="0" class="comment-tree">
              <tbody>
                <%= render 'comments/show', :object => @comments = Comment.where(contribution_id: @contribution.id, parent_id: nil) %>
              </tbody>
            </table>
            
            
          </tbody>
        </table>
      </td>
    </tr>
    
    

  </tbody>
</table>
</center> 